services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: drobe
      POSTGRES_PASSWORD: drobe
      POSTGRES_DB: drobebook
    volumes:
      - drobebook_pg:/var/lib/postgresql/data

volumes:
  drobebook_pg:
